{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d09d4027-5fb5-4e61-b8ed-8078a34a1752",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import os\n",
    "from sqlalchemy import create_engine, inspect\n",
    "from sqlalchemy.engine import URL\n",
    "import logging\n",
    "import time\n",
    "\n",
    "# ---------- Logging ----------\n",
    "os.makedirs(\"logs\", exist_ok=True)\n",
    "\n",
    "logging.basicConfig(\n",
    "    filename=\"logs/project_business.log\",\n",
    "    level=logging.INFO,\n",
    "    format=\"%(asctime)s - %(levelname)s - %(message)s\",\n",
    "    filemode=\"a\"\n",
    ")\n",
    "\n",
    "# ---------- MySQL Connection ----------\n",
    "url = URL.create(\n",
    "    drivername=\"mysql+pymysql\",\n",
    "    username=\"root\",\n",
    "    password=\"Macebox@1315\",\n",
    "    host=\"localhost\",\n",
    "    port=3306,\n",
    "    database=\"project_business\"\n",
    ")\n",
    "\n",
    "engine = create_engine(\n",
    "    url,\n",
    "    pool_recycle=3600,\n",
    "    pool_pre_ping=True,\n",
    "    echo=False,\n",
    "    future=True\n",
    ")\n",
    "\n",
    "# ---------- Connection Test ----------\n",
    "try:\n",
    "    with engine.connect():\n",
    "        print(\"✅ MySQL Connected Successfully!\")\n",
    "except Exception as e:\n",
    "    print(\"❌ Connection Error:\", e)\n",
    "    raise SystemExit(e)\n",
    "\n",
    "\n",
    "# ---------- Upload Function ----------\n",
    "def ingest_excel(file_path, table_name, engine):\n",
    "\n",
    "    inspector = inspect(engine)\n",
    "\n",
    "    if table_name in inspector.get_table_names():\n",
    "        print(f\"⚠️ Table '{table_name}' already exists — skipping...\")\n",
    "        logging.warning(f\"Table {table_name} already exists.\")\n",
    "        return\n",
    "\n",
    "    try:\n",
    "        start_time = time.time()\n",
    "\n",
    "        # ⭐ Read Excel\n",
    "        df = pd.read_excel(file_path)\n",
    "\n",
    "        print(f\"📊 Uploading {table_name} | Rows: {len(df)}\")\n",
    "        logging.info(f\"Uploading {table_name} with {len(df)} rows\")\n",
    "\n",
    "        # ⭐ SAFE chunk size\n",
    "        chunk_size = 20000\n",
    "\n",
    "        for start in range(0, len(df), chunk_size):\n",
    "            chunk = df.iloc[start:start+chunk_size]\n",
    "\n",
    "            chunk.to_sql(\n",
    "                table_name,\n",
    "                con=engine,\n",
    "                if_exists='append',\n",
    "                index=False,\n",
    "                method='multi'\n",
    "            )\n",
    "\n",
    "        total = (time.time() - start_time) / 60\n",
    "\n",
    "        print(f\"✅ {table_name} uploaded in {total:.2f} minutes\")\n",
    "        logging.info(f\"{table_name} uploaded successfully in {total:.2f} minutes\")\n",
    "\n",
    "    except Exception as e:\n",
    "        print(f\"❌ Error uploading {table_name}: {e}\")\n",
    "        logging.error(f\"Error uploading {table_name}: {e}\")\n",
    "\n",
    "\n",
    "# ---------- Load All Excel Files ----------\n",
    "def load_raw_data():\n",
    "\n",
    "    data_folder = \"data\"\n",
    "    start = time.time()\n",
    "\n",
    "    if not os.path.exists(data_folder):\n",
    "        raise FileNotFoundError(\"❌ 'data' folder not found!\")\n",
    "\n",
    "    for file in os.listdir(data_folder):\n",
    "\n",
    "        if file.endswith(\".xlsx\"):   # ✅ CORRECT EXTENSION\n",
    "\n",
    "            file_path = os.path.join(data_folder, file)\n",
    "\n",
    "            table_name = file.replace(\".xlsx\", \"\").lower()\n",
    "\n",
    "            logging.info(f\"🚀 Uploading {table_name} ...\")\n",
    "            ingest_excel(file_path, table_name, engine)\n",
    "\n",
    "    total_time = (time.time() - start) / 60\n",
    "\n",
    "    logging.info(\"🔥 ALL DATA UPLOADED SUCCESSFULLY!\")\n",
    "    logging.info(f\"Total Time Taken {total_time:.2f} minutes\")\n",
    "\n",
    "    print(f\"\\n🔥 ALL DATA UPLOADED IN {total_time:.2f} MINUTES\")\n",
    "\n",
    "\n",
    "# ---------- Run ----------\n",
    "load_raw_data()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
